### ISSUE TITLE
Todo before releasing 0.1

### ISSUE THREAD

**Issue by IainNZ** [IainNZ/JuMPeR.jl#49]
@vgupta1 

Target release for Wednesday, recitation is Friday.

* [x] Finish off docs (http://iainnz.github.io/JuMPeR.jl/) - just need ellipsoidal constraints, and oracle syntax
* [x] Re-consider how oracles are attached to constraints, given we use macros everywhere
* [x] Tag JuMP v0.8 so can use new print/solve hooks to kill `printRobust`/`solveRobust`
* [x] Also address callback deprecation warnings
* [x] Go through tests again

**Comment by vgupta1** [comment]
Awesome.  Is there anything I can help with on this list?  What do you think needs doing right now on DDUS.jl?  I'd think:

- [ ] Clean up the read me.
- [ ] Add more examples.  Suggestions on what to add here are welcome/appreciated.

Is there anything you think I'm missing?

**Comment by IainNZ** [comment]
DDUs is looking pretty good, documentation of the arguments to each oracle is the most important thing, caveats and guides to usage.

**Comment by vgupta1** [comment]
Would you stick that documentation in the read me or else in source code?

**Comment by IainNZ** [comment]
I think either is fine, as long as its clear from the README where to look.

**Comment by IainNZ** [comment]
Punting on per-constraint oracle syntax until its needed.
